#!/bin/bash

## prepare
PWD=$(pwd)
WORKDIR=work_dotfile

if [ ! -d ${WORKDIR} ]; then
  mkdir -p ${WORKDIR}
fi
cd ${WORKDIR}

if [ "$(uname)" == 'Darwin' ]; then
  OS='Mac'
  MITAMAE_URL=https://github.com/itamae-kitchen/mitamae/releases/download/v1.5.6/mitamae-x86_64-darwin
elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
  OS='Linux'
  MITAMAE_URL=https://github.com/itamae-kitchen/mitamae/releases/download/v1.5.6/mitamae-x86_64-linux

  # if ubuntu
  sudo apt-get install -y unzip
elif [ "$(expr substr $(uname -s) 1 10)" == 'MINGW32_NT' ]; then
  OS='Cygwin'
  echo "Your platform ($(uname -a)) is not supported."
  exit 1
else
  echo "Your platform ($(uname -a)) is not supported."
  exit 1
fi


DOTFILEDIR=dotfiles-new_dotfiles
if [ ! -d ${DOTFILEDIR} ]; then
  dotfile_github_url=https://github.com/bundai223/dotfiles/archive/new_dotfiles.zip
  wget $dotfile_github_url
  unzip new_dotfiles.zip
fi

cd $DOTFILEDIR

if [ ! -e bin/mitamae ]; then
  mkdir -p bin
  wget ${MITAMAE_URL} -O bin/mitamae
  chmod +x bin/mitamae
fi

# Homebrew does not allow sudo.
case "$(uname)" in
  "Darwin")  bin/mitamae local $@ lib/recipe.rb ;;
  *) sudo -i $(pwd)/bin/mitamae local $@ $(pwd)/lib/recipe.rb" ;;
esac
  #*) sudo -E bin/mitamae local $@ lib/recipe.rb ;;

## finish
cd $PWD
