#!/usr/local/bin/zsh
git_change_commiter()
{
  target_email="localhost@localhost.com"

  dst_author="bundai223"
  dst_email="bundai223@gmail.com"

  # refs) https://git-scm.com/book/ja/v1/Git-%E3%81%AE%E3%81%95%E3%81%BE%E3%81%96%E3%81%BE%E3%81%AA%E3%83%84%E3%83%BC%E3%83%AB-%E6%AD%B4%E5%8F%B2%E3%81%AE%E6%9B%B8%E3%81%8D%E6%8F%9B%E3%81%88#%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%81%AE%E5%88%86%E5%89%B2
  git filter-branch --commit-filter "
    if [ \"\$GIT_COMMITTER_EMAIL\" = $target_email ];
    then
      GIT_COMMITTER_NAME=\"$dst_author\";
      GIT_AUTHOR_NAME=\"$dst_author\";
      GIT_COMMITTER_EMAIL=\"$dst_email\";
      GIT_AUTHOR_EMAIL=\"$dst_email\";
      git commit-tree \"$@\";
    else
      git commit-tree \"$@\";
    fi" HEAD
}

git_change_commiter
