#!/usr/bin/env ruby
#

# commitメーセージに情報を追加するスクリプト。
# .git/hooks/prepare-commit-msg に配置する。
# ブランチ名にチケット番号などがついていたら参照設定を行う。

# コミットメッセージのテンプレ追加
if ARGV[1] && ARGV[1].include?("message")
  files = `git diff --cached --name-only`
  change_files = files.split("\n")

  prefix = []
  commit_messages = File.readlines(ARGV[0]).join("")

  # Mergeメッセージ以外はbranchのissue番号をrefsで記述する
  if not commit_messages.include?("Merge")
    message = commit_messages
    branch_raw = `git rev-parse --abbrev-ref HEAD`
    # todo: release/hotfixに対応
    issue_no = branch_raw.match(/feature\/(\d+)\//)
    if issue_no != nil
      puts "Add issueNo.#{issue_no[1]}"
    end
    open(ARGV[0], 'w') do |file|
      if issue_no != nil
        file.print("refs ##{issue_no[1]} ")
      end
      file.puts message
    end
  else
  end
end
