#!/bin/bash
#
# author: orefalo

hookname=$(basename $0)
hookdir=$(dirname $0)


f=$(mktemp)
trap 'rm -f $f' EXIT
cat - > $f

for hook in $hookdir/$hookname.*
do
  if test -x "$hook"; then
    # echo $hook
    cat $f | $hook "$@"
    status=$?

    if test $status -ne 0; then
      echo Hook $hook failed with error code $status
      exit $status
    fi
  fi
done
