#!/bin/bash
#
# author: orefalo
# set -eu

hookname=$(basename $0)
hookdir=$(dirname $0)


FILE=$(mktemp)
trap 'rm -f $FILE' EXIT
cat - > $FILE

for hook in $hookdir/$hookname.*
do
  if test -x "$hook"; then
    # echo $hook
    cat $FILE | $hook "$@"
    status=$?
    # echo "$hook: $?"

    if test $status -ne 0; then
      echo Hook $hook failed with error code $status
      exit $status
    fi
  fi
done
